package com.khrux.argent.datagen;

import com.khrux.argent.world.entity.ArgentEntityTypes;
import com.khrux.argent.world.item.ArgentItems;
import com.khrux.argent.world.item.enchantment.ArgentEnchantments;
import com.khrux.argent.world.level.block.ArgentBlocks;
import java.util.concurrent.CompletableFuture;
import net.fabricmc.fabric.api.datagen.v1.FabricPackOutput;
import net.fabricmc.fabric.api.datagen.v1.provider.FabricLanguageProvider;
import net.minecraft.core.HolderLookup;
import net.minecraft.util.Util;

public class ArgentLanguageProvider extends FabricLanguageProvider {
	public ArgentLanguageProvider(final FabricPackOutput output, final CompletableFuture<HolderLookup.Provider> registries) {
		super(output, registries);
	}

	@Override
	public void generateTranslations(final HolderLookup.Provider registries, final FabricLanguageProvider.TranslationBuilder translationBuilder) {
		translationBuilder.add(ArgentBlocks.SILVER_ORE, "Silver Ore");
		translationBuilder.add(ArgentBlocks.DEEPSLATE_SILVER_ORE, "Deepslate Silver Ore");
		translationBuilder.add(ArgentItems.RAW_SILVER, "Raw Silver");
		translationBuilder.add(ArgentItems.SILVER_INGOT, "Silver Ingot");
		translationBuilder.add(ArgentItems.SILVER_NUGGET, "Silver Nugget");
		translationBuilder.add(ArgentBlocks.SILVER_BLOCK, "Block of Silver");
		translationBuilder.add(ArgentBlocks.RAW_SILVER_BLOCK, "Block of Raw Silver");
		translationBuilder.add(ArgentBlocks.MIRROR, "Mirror");
		translationBuilder.add(ArgentBlocks.SILVER_BELL, "Silver Bell");
		translationBuilder.add(ArgentItems.REFLECTIVE_SHIELD, "Reflective Shield");
		translationBuilder.add(ArgentEntityTypes.WITHER_ZOMBIE, "Wither Zombie");
		translationBuilder.add(ArgentItems.WITHER_ZOMBIE_SPAWN_EGG, "Wither Zombie Spawn Egg");
		translationBuilder.add(Util.makeDescriptionId("enchantment", ArgentEnchantments.SCRYING.identifier()), "Scrying");
		translationBuilder.add(ArgentItems.SILVER_PARROT_ARMOR, "Silver Parrot Armor");
		translationBuilder.add("subtitles.entity.wither_zombie.ambient", "Wither Zombie groans");
		translationBuilder.add("subtitles.entity.wither_zombie.hurt", "Wither Zombie hurts");
		translationBuilder.add("subtitles.entity.wither_zombie.death", "Wither Zombie dies");
		translationBuilder.add("subtitles.entity.wither_zombie.notice", "Wither Zombie watches you");
		translationBuilder.add("subtitles.entity.wither_zombie.shatter", "Wither Zombie shatters");
		translationBuilder.add("options.argent.title", "Argent Settings");
		translationBuilder.add("options.argent.open_skin_editor", "Open Skin Editor...");
		translationBuilder.add("key.category.argent.argent", "Argent");
		translationBuilder.add("key.argent.open_skin_editor", "Open Skin Editor");
		translationBuilder.add("options.argent.silver", "Silver");
		translationBuilder.add("options.argent.silver.tooltip", "Silver ore generates, and silver items appear in the creative inventory. Existing silver stays. Ore changes apply to newly generated chunks after rejoining.");
		translationBuilder.add("options.argent.mirror_recipe", "Mirror Recipe");
		translationBuilder.add("options.argent.mirror_recipe.tooltip", "Whether mirrors can be crafted, and from what. Off also hides them from the creative inventory; existing mirrors stay. Applies after /reload or rejoining.");
		translationBuilder.add("options.argent.mirror_recipe.off", "Off");
		translationBuilder.add("options.argent.mirror_recipe.silver", "Silver");
		translationBuilder.add("options.argent.mirror_recipe.diamond", "Diamond");
		translationBuilder.add("options.argent.soul_lantern", "Soul Lantern");
		translationBuilder.add("options.argent.soul_lantern.tooltip", "Where a soul lantern must be for soul particles to rise where monsters can spawn. Off also removes the iron and silver nugget recipe.");
		translationBuilder.add("options.argent.soul_lantern.off", "Off");
		translationBuilder.add("options.argent.soul_lantern.hand", "In Hand");
		translationBuilder.add("options.argent.soul_lantern.inventory", "In Inventory");
		translationBuilder.add("options.argent.reflections", "Reflections");
		translationBuilder.add("options.argent.reflections.tooltip", "What mirrors reflect. Entities Only is faster: players, mobs and items over plain glass.");
		translationBuilder.add("options.argent.reflections.off", "Off");
		translationBuilder.add("options.argent.reflections.entities", "Entities Only");
		translationBuilder.add("options.argent.reflections.all", "Everything");
		translationBuilder.add("options.argent.skin_editor_key", "Editor Key: %s");
		translationBuilder.add("options.argent.scrying", "Scrying");
		translationBuilder.add("options.argent.scrying.tooltip", "Whether sneaking and using an empty hand on your pet wearing Scrying armour lets you see and move through it.");
		translationBuilder.add("options.argent.wither_zombies", "Wither Zombies");
		translationBuilder.add("options.argent.wither_zombies.tooltip", "Whether wither zombies spawn in the Nether. Existing ones stay.");
		translationBuilder.add("options.argent.mirror_screen", "Mirror Screen");
		translationBuilder.add("options.argent.mirror_screen.tooltip", "Off makes mirrors props: right-clicking does nothing.");
		translationBuilder.add("gui.argent.preset", "Preset %s");
		translationBuilder.add("gui.argent.layer.base", "Base layer: click a part to hide or show it");
		translationBuilder.add("gui.argent.layer.overlay", "Overlay layer: click a part to hide or show it");
		translationBuilder.add("gui.argent.arm_width.slim", "Arms: Slim (3px)");
		translationBuilder.add("gui.argent.arm_width.wide", "Arms: Wide (4px)");
		translationBuilder.add("gui.argent.reset_view", "Reset view");
		translationBuilder.add("gui.argent.face", "%s - %s");
		translationBuilder.add("gui.argent.face.none", "Click the model");
		translationBuilder.add("gui.argent.part.head", "Head");
		translationBuilder.add("gui.argent.part.hat", "Hat");
		translationBuilder.add("gui.argent.part.body", "Body");
		translationBuilder.add("gui.argent.part.jacket", "Jacket");
		translationBuilder.add("gui.argent.part.right_arm", "Right arm");
		translationBuilder.add("gui.argent.part.right_sleeve", "Right sleeve");
		translationBuilder.add("gui.argent.part.left_arm", "Left arm");
		translationBuilder.add("gui.argent.part.left_sleeve", "Left sleeve");
		translationBuilder.add("gui.argent.part.right_leg", "Right leg");
		translationBuilder.add("gui.argent.part.right_pants", "Right trouser leg");
		translationBuilder.add("gui.argent.part.left_leg", "Left leg");
		translationBuilder.add("gui.argent.part.left_pants", "Left trouser leg");
		translationBuilder.add("gui.argent.side.down", "top");
		translationBuilder.add("gui.argent.side.up", "bottom");
		translationBuilder.add("gui.argent.side.north", "front");
		translationBuilder.add("gui.argent.side.south", "back");
		translationBuilder.add("gui.argent.side.west", "right");
		translationBuilder.add("gui.argent.side.east", "left");
		translationBuilder.add("gui.argent.tool.pencil", "Pencil");
		translationBuilder.add("gui.argent.tool.fill", "Fill");
		translationBuilder.add("gui.argent.tool.eraser", "Eraser (overlay layer only)");
		translationBuilder.add("gui.argent.import.field", "Import a skin");
		translationBuilder.add("gui.argent.import.hint", "Skin URL, username or UUID");
		translationBuilder.add("gui.argent.import", "Import");
		translationBuilder.add("gui.argent.import.failed", "Couldn't import skin");
		translationBuilder.add("gui.argent.file", "File");
		translationBuilder.add("gui.argent.file.tooltip", "Open the presets folder. To import a PNG, drop it onto this screen.");
		translationBuilder.add("gui.argent.reset", "Reset");
		translationBuilder.add("gui.argent.upload", "Upload");
		translationBuilder.add("gui.argent.upload.tooltip", "Upload the selected preset as your Minecraft skin");
		translationBuilder.add("gui.argent.upload.title", "Upload preset %s?");
		translationBuilder.add("gui.argent.upload.message", "This replaces your skin on your Minecraft account, for every server and launcher.");
		translationBuilder.add("gui.argent.upload.done", "Skin uploaded");
		translationBuilder.add("gui.argent.upload.failed", "Couldn't upload skin");
		translationBuilder.add("gui.argent.rejoin.title", "Rejoin to show your new skin?");
		translationBuilder.add("gui.argent.rejoin.message", "Other players on %s see your new skin after you rejoin.");
		translationBuilder.add("gui.argent.reset.title", "Reset preset %s?");
		translationBuilder.add("gui.argent.reset.message", "It goes back to its default skin. Undo can bring your painting back while this screen stays open.");
		translationBuilder.add("gui.argent.tool.picker", "Colour picker");
		translationBuilder.add("gui.argent.undo", "Undo (Ctrl+Z)");
		translationBuilder.add("gui.argent.redo", "Redo (Ctrl+Y)");
		translationBuilder.add("gui.argent.colour", "Colour");
		translationBuilder.add("gui.argent.palette", "Recent colours");
	}
}
